general.import = ["/Users/teekm/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]

# normal = { family = "FiraCode Nerd Font", style = "Regular" }
# bold = { family = "FiraCode Nerd Font", style = "Bold" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }

bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# size = 12 # Laptop
size = 14 # Regular
# size = 16 # HDR

[font.offset]
x = 1
y = 1

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "tmux"]

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.90

[window.padding]
x = 2
y = 2

[[keyboard.bindings]]
key = "H"
mods = "Control"
chars = "\u001b[D"

[[keyboard.bindings]]
key = "J"
mods = "Control"
chars = "\u001b[B"

[[keyboard.bindings]]
key = "K"
mods = "Control"
chars = "\u001b[A"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\u001b[C"

# Colors (Gruvbox dark)

# Default colors
# [colors.primary]
# hard contrast background = = '#1d2021'
# soft contrast background = = '#32302f'
# background = '#1d2021'
# background = '#282828'
# foreground = '#ebdbb2'

# Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'
#
# Bright colors
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'
